name: app_de_viajes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tokio.webp
    - assets/paris.jpg
    - assets/new_york.jpg
    - assets/londres.jpg
    - assets/roma.jpg
